// styles/chat.styles.ts
import { StyleSheet, Platform } from "react-native";
import COLORS from "../../constants/colors";
import {
    SPACING,
    PADDING,
    FONT_SIZE,
    TYPOGRAPHY,
    BORDER_RADIUS,
    RADIUS,
    SHADOWS,
    COMPONENT_SIZES,
    BORDER_WIDTH,
    OPACITY,
} from "../../constants/styleConstants";

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: COLORS.background,
    },
    headerRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: SPACING.lg,
    },
    headerAvatar: {
        width: 40,
        height: 40,
        borderRadius: 20,
        borderWidth: 1.5,
        borderColor: COLORS.diamondRim,
    },
    avatarContainer: {
        position: 'relative',
    },
    statusDot: {
        position: 'absolute',
        bottom: 0,
        right: 0,
        width: 12,
        height: 12,
        borderRadius: 6,
        backgroundColor: COLORS.success,
        borderWidth: 2,
        borderColor: COLORS.background,
    },
    headerInfo: {
        justifyContent: 'center',
    },
    headerName: {
        fontSize: FONT_SIZE.lg,
        fontWeight: '900',
        color: COLORS.textPrimary,
        letterSpacing: 0.5,
    },
    headerStatus: {
        fontSize: 10,
        color: COLORS.primary,
        fontWeight: '800',
        textTransform: 'uppercase',
        letterSpacing: 1,
    },
    messagesList: {
        paddingVertical: SPACING.xl,
        paddingHorizontal: SPACING.lg,
    },
    messageContainer: {
        width: '100%',
        flexDirection: 'row',
        marginBottom: SPACING.md,
        alignItems: 'flex-end',
        gap: SPACING.sm,
    },
    myMessage: {
        justifyContent: 'flex-end',
    },
    theirMessage: {
        justifyContent: 'flex-start',
    },
    messageAvatar: {
        width: 28,
        height: 28,
        borderRadius: 14,
        borderWidth: 1,
        borderColor: COLORS.glassBorder,
        marginBottom: 2,
    },
    messageBubble: {
        maxWidth: '85%',
        paddingHorizontal: 18,
        paddingVertical: 12,
        borderRadius: 22,
        position: 'relative',
        minWidth: 60,
    },
    myBubble: {
        backgroundColor: COLORS.primary,
        borderBottomRightRadius: 4,
        ...SHADOWS.aura,
    },
    theirBubble: {
        backgroundColor: COLORS.surfaceSilk,
        borderBottomLeftRadius: 4,
        borderWidth: 1,
        borderColor: COLORS.glassBorder,
        ...SHADOWS.medium,
    },
    imageBubble: {
        padding: 4,
        backgroundColor: COLORS.surfaceSilk,
        borderWidth: 1,
        borderColor: COLORS.glassBorder,
        ...SHADOWS.godLevel,
    },
    deletedBubble: {
        opacity: 0.6,
        backgroundColor: 'rgba(255, 255, 255, 0.05)',
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.1)',
    },
    deletedText: {
        fontStyle: 'italic',
        fontSize: 12,
    },
    editedLabel: {
        fontSize: 9,
        fontWeight: '700',
        fontStyle: 'italic',
    },
    sentImage: {
        borderRadius: 18,
        backgroundColor: COLORS.surfaceHighlight,
        overflow: 'hidden',
    },
    sentVideoContainer: {
        width: 240,
        height: 180,
        borderRadius: 18,
        overflow: 'hidden',
        backgroundColor: COLORS.surfaceHighlight,
        position: 'relative',
    },
    sentVideo: {
        width: '100%',
        height: '100%',
    },
    sentVideoThumbnail: {
        width: '100%',
        height: '100%',
    },
    playButtonOverlay: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: 'rgba(0,0,0,0.3)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    pendingIndicator: {
        marginLeft: 4,
        width: 14,
        height: 14,
        justifyContent: 'center',
        alignItems: 'center',
    },
    messageText: {
        fontSize: 15,
        lineHeight: 22,
        fontWeight: '500',
        letterSpacing: 0.2,
    },
    myText: {
        color: '#000',
        fontWeight: '700',
    },
    theirText: {
        color: COLORS.textPrimary,
    },
    messageTime: {
        fontSize: 10,
        marginTop: 4,
        fontWeight: '800',
        alignSelf: 'flex-end',
        opacity: 0.6,
    },
    myTime: {
        color: 'rgba(0,0,0,0.6)',
    },
    theirTime: {
        color: COLORS.textMuted,
    },
    inputWrapper: {
        paddingHorizontal: 20,
        paddingBottom: Platform.OS === 'ios' ? 30 : 20,
        backgroundColor: 'transparent',
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
    },
    inputContainer: {
        flexDirection: 'row',
        backgroundColor: 'rgba(14, 27, 36, 0.95)',
        borderRadius: 30,
        padding: 6,
        alignItems: 'flex-end',
        borderWidth: 1.2,
        borderColor: COLORS.diamondRim,
        ...SHADOWS.godLevel,
    },
    input: {
        flex: 1,
        maxHeight: 120,
        color: COLORS.textPrimary,
        fontSize: 16,
        fontWeight: '600',
        paddingHorizontal: 16,
        paddingVertical: 10,
    },
    iconButton: {
        width: 44,
        height: 44,
        borderRadius: 22,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(255, 255, 255, 0.05)',
    },
    sendButton: {
        backgroundColor: COLORS.primary,
        width: 44,
        height: 44,
        borderRadius: 22,
        justifyContent: 'center',
        alignItems: 'center',
        ...SHADOWS.aura,
    },
    sendButtonDisabled: {
        backgroundColor: 'rgba(255, 255, 255, 0.1)',
        opacity: 0.5,
    },
    emptyContainer: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        paddingTop: 100,
        paddingHorizontal: SPACING.massive,
    },
    emptyIconCircle: {
        width: SPACING.colossal,
        height: SPACING.colossal,
        borderRadius: SPACING.massive,
        backgroundColor: 'rgba(255, 255, 255, 0.05)',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: SPACING.xxl,
    },
    emptyText: {
        fontSize: FONT_SIZE.base,
        color: COLORS.textMuted,
        fontWeight: '600',
        textAlign: 'center',
        lineHeight: 22,
    },
    // Image Preview Styles
    previewOverlay: {
        flex: 1,
        backgroundColor: COLORS.black,
        justifyContent: 'space-between',
    },
    previewHeader: {
        flexDirection: 'row',
        padding: SPACING.xl,
        paddingTop: Platform.OS === 'ios' ? 60 : SPACING.xl,
        justifyContent: 'flex-start',
    },
    previewImageContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: SPACING.md,
    },
    previewImageWrapper: {
        width: '100%',
        aspectRatio: 1,
        borderRadius: BORDER_RADIUS.xl,
        overflow: 'hidden',
        borderWidth: BORDER_WIDTH.thin,
        borderColor: COLORS.glassBorder,
        ...SHADOWS.extraStrong,
    },
    previewImage: {
        width: '100%',
        height: '100%',
    },
    previewFooter: {
        flexDirection: 'row',
        padding: SPACING.xxl,
        paddingBottom: Platform.OS === 'ios' ? 40 : SPACING.huge,
        justifyContent: 'flex-end',
        alignItems: 'center',
    },
    previewSendButton: {
        width: 60,
        height: 60,
        borderRadius: 30,
        backgroundColor: COLORS.primary,
        justifyContent: 'center',
        alignItems: 'center',
        ...SHADOWS.strong,
        shadowColor: COLORS.primary,
    },
    closeButton: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: 'rgba(255,255,255,0.1)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    // Book Card Styles
    bookCard: {
        width: 200,
        backgroundColor: 'rgba(255,255,255,0.05)',
        borderRadius: 16,
        overflow: 'hidden',
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.1)',
        marginBottom: 4,
    },
    bookCardImage: {
        width: '100%',
        height: 260,
        backgroundColor: COLORS.surfaceHighlight,
    },
    bookCardContent: {
        padding: 12,
    },
    bookCardTitle: {
        fontSize: 14,
        fontWeight: '900',
        color: COLORS.textPrimary,
        marginBottom: 2,
    },
    bookCardAuthor: {
        fontSize: 12,
        color: COLORS.textSecondary,
        fontWeight: '600',
        marginBottom: 8,
    },
    bookCardViewBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
        backgroundColor: 'rgba(255,255,255,0.05)',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 8,
        alignSelf: 'flex-start',
    },
    bookCardViewBtnText: {
        fontSize: 11,
        fontWeight: '800',
        color: COLORS.primary,
        textTransform: 'uppercase',
    },
});

export default styles;
